name: 'Hello (Python)'
description: 'Greet someone and expose a greeting output'
inputs:
  who-to-greet:
    description: 'Name to greet'
    required: true
    default: 'World'
outputs:
  greeting:
    description: 'The greeting that was printed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}

