name: Run Greeting Workflow

on: [push]

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run local action
        uses: ./.
        id: hello
        with:
          who-to-greet: 'Mona Lisa'

      - name: Print the output
        run: echo "The action said ${{ steps.hello.outputs.greeting }}"

